### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by MuhammedAman113114** [Antu7/python-bruteForce#27]
$ python bruteforce.py
Traceback (most recent call last):
  File "C:\Users\Aman\python-bruteForce\bruteforce.py", line 8, in <module>
    print ("""
    ^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 5-11: character maps to <undefined>

**Comment by Antu7** [comment]
I think your machine is not properly pyhon3 installed.
